name: Main

# Quick way to trigger a workflow by starring this repo.
on: watch

jobs:
  build:
    # This only runs when `francisfuzz` stars the repo.
    if: github.actor == 'francisfuzz'

    # Runs this job once for every listed runner in `matrix.os`.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-16.04, macos-latest]
        times-to-run: [1, 2, 3, 4, 5]
      fail-fast: false
    
    steps:

    # https://opensource.apple.com/source/apache/apache-643/printenv.auto.html
    # https://manpages.ubuntu.com/manpages/bionic/man1/printenv.1.html
    - if: runner.os == 'macOS' || runner.os == 'Linux'
      run: |
        printenv

    - name: Assert GITHUB_RUN_ID exists (*nix)
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: |
        if [ -z "${GITHUB_RUN_ID}" ]; then
          exit 0
        else
          exit 1
        fi

    # https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-powershell-1.0/ff730964(v=technet.10)
    - if: runner.os == 'Windows'
      run: |
        Get-ChildItem Env:

    - name: Assert GITHUB_RUN_ID exists (Windows)
      if: runner.os == 'Windows'
      run: |
        if (Get-Variable 'GITHUB_RUN_ID' -Scope 'Global') {
          exit 0
        } else {
          exit 1
        } 
